version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always

  recortador:
    build: .
    container_name: recortador
    ports:
      - 80:80
    depends_on:
      - redis
    restart: always
